name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken
      - uses: actions/checkout@v4

      # 2. Logge dich in die GitHub Container Registry ein
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Baue das Docker-Image
      - name: Build the Docker image
        run: docker build . --file Containerfile --tag ghcr.io/${{ github.repository }}:latest

      # 4. Pushe das Docker-Image in die Registry
      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}:latest
